<?php
/* start typography classes */
$typographyclasses = array(
    "body" => "Main Typography",
    "a" => "Site Links",
    "h1" => "h1",
    "h2" => "h2",
    "h3" => "h3",
    "h4" => "h4",
    "h5" => "h5",
    "h6" => "h6",
    ".contact_info_item a" => "Header Contact Info",
    ".navbar .main_nav .nav>li>a" => "Main Main Menu",
    ".expanded_search.header_search input[type='text']" => "Header Search",
    ".section_title h2" => "Section Title",
    ".section_description" => "Section Description",
    ".service_title" => "Service Block Title",
    ".service_body p" => "Service Text",
    "push_button_info > h2" => "Action Button Title",
    "push_button_info p" => "Action Button Text",
    ".header_top, .contact_info_item, .contact_info_item > i, .contact_info_item a" => "Top Header Texts",
    ".logo a" => "Logo color",
    "#lang_sel a, a.lang_sel_sel, #lang_sel a:visited, #lang_sel ul ul a, #lang_sel ul ul a:visited" => "WPML Language Switcher Text",
    "#lang_sel a:hover, a.lang_sel_sel:hover, #lang_sel ul ul a:hover" => "WPML Language Switcher Hover Text",
    ".overlay_button" => "Full Screen Menu",
    ".first_header_wrapper .navbar .nav>li>a" => "Main menu items",
    ".first_header_wrapper .navbar .nav>li>a:focus, .first_header_wrapper .navbar .nav>li>a:hover" => "Main Menu Item Hover Color",
    ".first_header_wrapper .navbar .nav>li>a>i" => "Main menu icons",
    ".first_header_wrapper .navbar .nav>li>a:hover>i" => "Main menu icons on hover",
    ".first_header_wrapper .navbar .nav .dropdown-menu li > a" => "Header Dropdown Menu Items",
    ".dropdown-menu > li > a" => "Dropdown Menu Items",
    ".dropdown-menu>li>a:hover, .dropdown-menu>li>a:focus" => "Dropdown menu Item Hover Color",
    ".header_social a" => "Header social icons color",
    ".header_social a:hover" => "Header social icons hover color",
    "input[type='text'].search_text" => "Search Form Text",
    ".side_content .widget_container h4.page-header" => "Sidebar Titles",
    ".side_content .widget_container" => "Sidebar Content",
    ".widget_content > ul > li a" => "Sidebar Links",
    ".side_content .postlist-widget .post_info .title a" => "Sidebar Post List Widget Titles",
    ".side_content .postlist-widget .post_info .post_time" => "Sidebar Post List Widget Time",
    ".tagcloud a" => "Tag Cloud",
    ".pagination>li>a" => "Pagination Text",
    ".pagination>li>a:hover" => "Pagination Hover Text",
    ".pagination>li>a.active" => "Active Pagination Text",
    ".site_footer" => "Site Footer Texts",
    ".site_footer .tagcloud a" => "Footer Sidebars Tagcloud",
    ".site_footer .page-header" => "Footer Sidebars Widget Titles",
    ".site_footer.dark_footer .widget_content > ul > li a" => "Site Footer Links",
    ".site_footer .postlist-widget .post_info .title a" => "Footer Post List Widget Titles",
    ".site_footer .postlist-widget .post_info .post_time" => "Footer Post List Widget Time",
    ".site_footer.dark_footer input[type='text'].search_text" => "Footer Search",
    ".footer_navbar .nav>li>a" => "Footer Menu Items",
    ".footer_navbar .nav>li>a:focus, .footer_navbar .nav>li>a:hover" => "Footer Menu Items Hover",
    ".footer_text" => "Footer Credits",
    ".blog_title h3, .blog_title h3>a" => "Default Blog Titles",
    ".blog_main_content .blog_description" => "Default Blog Description",
    ".blog_main_content.style_classic .blog_title h3, .blog_main_content.style_classic .blog_title h3>a" => "Classic Blog Titles",
    ".blog_main_content.style_classic .blog_description" => "Classic Blog Titles",
    ".blog_main_content.style_masonry .blog_title h3, .blog_main_content.style_masonry .blog_title h3>a" => "Masonry Blog Titles",
    ".blog_main_content.style_masonry .blog_description" => "Masonry Blog Description",
    ".single_main_content .blog_description" => "Inside Post Blog Description",
    ".meta_item, .meta_item a" => "Blog Meta Items",
    ".post_navigation_wrapper a" => "Posts And Projects (Next/Previous) Navigations",
    ".new_comment_box textarea, .new_comment_box input[type='text']" => "New Comment Inputs Texts",
    "input[type='submit']" => "Submit Buttons",
    "input[type='submit']:hover" => "Submit Buttons Hover",
    ".projects_wrapper.style_default figcaption.portfolio_caption .title" => "Default Style Portfolio Titles",
    ".projects_wrapper.style_classic figcaption.portfolio_caption .title" => "Classic Style Portfolio Titles",
    ".projects_wrapper.style_classic figcaption.portfolio_caption .portfolio_category" => "Classic Style Portfolio Categories",
    ".projects_wrapper.style_grid figcaption.portfolio_caption .title" => "Grid Style Portfolio Titles",
    ".projects_wrapper.style_text figcaption.portfolio_caption .title" => "Text Style Portfolio Titles",
    ".projects_wrapper.style_text figcaption.portfolio_caption .portfolio_category" => "Text Style Portfolio Categories",
    ".projects_wrapper.style_text .portfolio_caption .project_text" => "Text Style Portfolio Description",
    ".projects_wrapper.style_full figcaption.portfolio_caption .title" => "Full Style Portfolio Titles",
    ".portfolio_filter.navbar .nav>li>a" => "Portfolio Filter Items",
    ".portfolio_filter.navbar .nav>.active>a" => "Portfolio Filter Selected Item",
    ".side_content .project_info_container .widget_container h4.page-header" => "Inside Project Title",
    ".side_content .widget_container.project_description_content" => "Project Description Text",
    ".project_details_item" => "Project Details Texts",
    ".project_details_item a" => "Project Details Links",
    "form p" => "Form Labels",
    ".woocommerce ul.products li.product h3, .woocommerce-page ul.products li.product h3" => "Shop Page Products Titles",
    ".woocommerce ul.products li.product .price, .woocommerce-page ul.products li.product .price" => "Shop Page Products Prices",
    "ul.products li.product .add_to_cart_button.button.button.product_type_simple" => "Shop Page Add To Cart",
    ".woocommerce ul.products li.product .price del" => "Shop Page Before Sale Price",
    ".woocommerce-page div.product .product_title" => "Product Title",
    "div.product p.price, .woocommerce-page div.product p.price" => "Product Price",
    ".woocommerce-page div.product .woocommerce-tabs ul.tabs li a" => "Product Details Tab Title",
    ".woocommerce div.product .woocommerce-tabs .panel, .woocommerce-page div.product .woocommerce-tabs .panel" => "Product Details Tabs Text",
    ".page_title_holder h1" => "Page Title Holder",
    ".page_title_holder .breadcrumb" => "Breadcrumb Text",
    ".page_title_holder a" => "Breadcrumb Links",
);

$fontsclasses = array(
    "body" => "Main Font",
    "h1, h2, h3, h4, h5, h6, h7, h8, .title, .thin_title, .thin_heading, blockquote p, th, .pricingcontainer .plans .plan_title, .su-dropcap-style-simple, .su-pullquote" => "Titles Font",
    ".navbar .main_nav .nav>li>a" => "Main Menu Items",
    ".logo a" => "Logo"
);

$colorclasses = array(
    "html" => "HTML (All Site Body)",
    "body" => "Site Body",
    ".header_top" => "Top Header",
    ".header_below" => "Main Header Area",
    ".overlay_button" => "Full Screen Menu",
    ".dropdown-menu" => "Dropdown Menu",
    ".dropdown-menu>li>a:hover, .dropdown-menu>li>a:focus" => "Dropdown menu item hover background",
    ".mega_menu > .dropdown-menu > li" => "Mega Menu Separator Border",
    ".expanded_search.header_search input[type='text']" => "Header search form background",
    "input[type='text'].search_text" => "Search Form Background",
    ".site_footer.dark_footer input[type='text'].search_text" => "Footer Search background",
    ".header_button .gototop > i" => "Go to top icon color",
    ".page_title_holder" => "Page Title Holder",
    ".tagcloud a" => "tag cloud background",
    ".footer-fluid" => "Footer Background",
    "#lang_sel a, a.lang_sel_sel, #lang_sel a:visited, #lang_sel ul ul a, #lang_sel ul ul a:visited" => "WPML Language Switcher Background",
    "#lang_sel a:hover, a.lang_sel_sel:hover, #lang_sel ul ul a:hover" => "WPML Language Switcher Hover Background",
    ".site_footer .tagcloud a" => "Footer tag cloud background",
    ".portfolio_filter.navbar .nav>li>a" => "Portfolio Filter Items Background",
    ".portfolio_filter.navbar .nav>.active>a" => "Portfolio Filter Selected Item Background",
    ".projects_wrapper.style_default .portfolio_figure .overlay_color" => "Default Portfolio Style Hover Overlay Color",
    ".projects_wrapper.style_grid .portfolio_figure .overlay_color" => "Grid Portfolio Style Hover Overlay Color",
    ".projects_wrapper.style_classic figcaption.portfolio_caption" => "Classic Portfolio Style Title Background",
    ".projects_wrapper.style_full figcaption.portfolio_caption" => "Full Portfolio Style Title Background",
    ".new_comment_box textarea, .new_comment_box input[type='text']" => "New Comment Inputs Background",
    "input[type='submit']" => "Submit Buttons",
    "input[type='submit']:hover" => "Submit Buttons Hover",
    ".woocommerce span.onsale, .woocommerce-page span.onsale, .woocommerce ul.products li.product .onsale, .woocommerce-page ul.products li.product .onsale" => "Shop Sale Label Background",
    ".woocommerce div.product div.images div.thumbnails a, .woocommerce-page div.product div.images div.thumbnails a" => "Product Gallery Background",
    ".pagination>li>a" => "Pagination Background",
    ".pagination>li>a:hover" => "Pagination Hover Background",
    ".pagination>li>a.active" => "Active Pagination Background",
    
);

$bordersclasses = array(
	".header_top" => "Top Header Border",
	".contact_info_item" => "Top Header contact info divider",
	".header_below" => "Main Header Border",
    ".first_header_wrapper .navbar .nav .dropdown-menu li > a" => "Header Dropdown Menu Items",
    ".dropdown-menu > li > a" => "Dropdown Menu Items",
    ".widget_content > ul > li" => "Sidebar Lists Separator Border",
    "input[type='text'].search_text" => "Search Form Borders",
    "#lang_sel a, a.lang_sel_sel, #lang_sel a:visited, #lang_sel ul ul a, #lang_sel ul ul a:visited" => "WPML Language Switcher Border",
	".expanded_search.header_search input[type='text']" => "Header search form border color",
    ".site_footer.dark_footer input[type='text'].search_text" => "Footer Search border color",
    ".site_footer .widget_content > ul > li" => "Footer Lists Border Color",
    ".second_footer" => "Divider between 2 footers",
    ".projects_wrapper.style_classic figcaption.portfolio_caption" => "Classic Portfolio Style Caption Border",
    ".projects_wrapper.style_text figcaption.portfolio_caption .portfolio_category" => "Text Portfolio Style Caption Border",
    ".post_navigation_wrapper" => "Posts And Projects (Next/Previous) Borders",
    ".blog_info_box" => "Blog Meta Info Borders",
    ".blog_main_content.style_masonry .blog_info_box" => "Masonry Blog Meta Info Borders",
    ".new_comment_box textarea, .new_comment_box input[type='text']" => "New Comment Inputs Border",
    ".woocommerce ul.products li.product h3, .woocommerce-page ul.products li.product h3" => "Shop Page Title Border",
    ".woocommerce div.product div.images div.thumbnails a, .woocommerce-page div.product div.images div.thumbnails a" => "Product Gallery Border",
    ".pagination>li>a" => "Pagination Border",
    ".pagination>li>a:hover" => "Pagination Hover Border",
    ".pagination>li>a.active" => "Active Pagination Border",

);

$bgclasses = array(// themes-style
    "html" => "HTML (All Site Background)",
    "body" => "Body (Content Area)",
    ".site_header" => "Header",
    ".site_footer" => "Footer",
    ".page_title_holder" => "Page Title Holder"
);

$textcolorsclasses = array(
	".header_search > i" => "Header search entire icon color",
	".header_button .gototop > i" => "Go to top entire arrow color",
    ".page_title_holder span.divider" => "Breadcrumb Divider",
    ".woocommerce span.onsale, .woocommerce-page span.onsale, .woocommerce ul.products li.product .onsale, .woocommerce-page ul.products li.product .onsale" => "Shop Sale Label Text Color",
	
);
?>
